// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRxVWMy_-mhhCR0GJMR2VDr3Cd4Nfrh10',
    appId: '1:254143810702:web:e36ac0e11fca9552338ddf',
    messagingSenderId: '254143810702',
    projectId: 'myfarm-ea0f2',
    authDomain: 'myfarm-ea0f2.firebaseapp.com',
    storageBucket: 'myfarm-ea0f2.firebasestorage.app',
    measurementId: 'G-FGRCMQWPQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABmnz_v4dRNpv2FxScPOk0XxrOUGHhcZc',
    appId: '1:254143810702:android:2fae41c9dadae9fd338ddf',
    messagingSenderId: '254143810702',
    projectId: 'myfarm-ea0f2',
    storageBucket: 'myfarm-ea0f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwiY4tDUNMo6Gl6aGotyucnisdQQ2dVDM',
    appId: '1:254143810702:ios:cce3f5c5652c4fc8338ddf',
    messagingSenderId: '254143810702',
    projectId: 'myfarm-ea0f2',
    storageBucket: 'myfarm-ea0f2.firebasestorage.app',
    iosBundleId: 'com.example.myfarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwiY4tDUNMo6Gl6aGotyucnisdQQ2dVDM',
    appId: '1:254143810702:ios:cce3f5c5652c4fc8338ddf',
    messagingSenderId: '254143810702',
    projectId: 'myfarm-ea0f2',
    storageBucket: 'myfarm-ea0f2.firebasestorage.app',
    iosBundleId: 'com.example.myfarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRxVWMy_-mhhCR0GJMR2VDr3Cd4Nfrh10',
    appId: '1:254143810702:web:0b6000a1f2251144338ddf',
    messagingSenderId: '254143810702',
    projectId: 'myfarm-ea0f2',
    authDomain: 'myfarm-ea0f2.firebaseapp.com',
    storageBucket: 'myfarm-ea0f2.firebasestorage.app',
    measurementId: 'G-R8QLRQ5WCH',
  );
}
